server {
    listen 80;
    listen [::]:80;
    server_name bestquiz.uz api.bestquiz.uz bot.bestquiz.uz;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        add_header "Access-Control-Allow-Origin" "*" always;
        return 301 https://$host$request_uri;
    }
}

server {
    listen 127.0.0.1:8443 ssl;
    http2 on;
    server_name bestquiz.uz api.bestquiz.uz bot.bestquiz.uz;

    ssl_certificate     /etc/letsencrypt/live/bestquiz.uz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bestquiz.uz/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    client_max_body_size 25m;

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 120s;
    }
}
